# /etc/nginx/conf.d/react_app.conf

server {
    listen 80;
    server_name _;  
    root /usr/share/nginx/html;  # Root directory where the built React app is located
    index index.html;  # Index file of the React application

    location / {
        # root   /usr/share/nginx/html;
        # index  index.html index.htm;
        # try_files $uri /index.html; 
        add_header 'X-Real-IP' "$remote_addr" always;
        try_files $uri $uri/ /index.html;  # Handling client-side routing
        error_page 404 =404 /404.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
    
}
