services:
  backend:
    image: smart-finance-backend:latest     # ⚠️ टैग बदलकर 'latest' किया गया है
    container_name: finance-backend-prod
    ports:
      - "8082:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/personal_finance_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin   # आपके कंप्यूटर के MySQL का असली पासवर्ड
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: smart-finance-frontend:latest    # ⚠️ टैग बदलकर 'latest' किया गया है
    container_name: finance-frontend-prod
    ports:
      - "3000:80"
    depends_on:
      - backend
